[package]
name = "maldives"
version = "0.1.0"
authors = ["David Vest <davve@davve.net>"]
edition = "2018"

[dependencies]
rustyline = "5.0.5"
log = "0.4.8"
dirs = "2.0"
env_logger = "0.7.1"
sdl2 = "0.34"
