[package]
name = "maldives"
version = "0.1.0"
authors = ["David Vest <davve@davve.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.103", features = [ "derive" ]}
serde_json = "1.0.44"
regex = "1.0"
